# Generated by Django 3.1.5 on 2021-01-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faktura',
            table='stavkakataloga',
        ),
    ]
