# Generated by Django 3.1.5 on 2021-01-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0002_auto_20210120_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='katalog',
            fields=[
                ('rednibroj', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'stavkakataloga',
            },
        ),
        migrations.DeleteModel(
            name='faktura',
        ),
    ]
