# Generated by Django 3.1.5 on 2021-01-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0003_auto_20210120_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='stavkakataloga',
            fields=[
                ('rednibroj', models.IntegerField(primary_key=True, serialize=False)),
                ('brojkataloga', models.CharField(max_length=25)),
                ('sifraartikla', models.CharField(max_length=25)),
                ('dimenzija', models.CharField(max_length=25)),
                ('cena', models.CharField(max_length=25)),
                ('pdv', models.CharField(max_length=25)),
                ('naziv', models.CharField(max_length=25)),
                ('nazivartikla', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'stavkakataloga',
            },
        ),
        migrations.DeleteModel(
            name='katalog',
        ),
    ]
