# Generated by Django 3.1.5 on 2021-01-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0004_auto_20210121_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stavkakataloga',
            new_name='katalog',
        ),
    ]
