# Generated by Django 3.1.5 on 2021-01-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0005_auto_20210121_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='artikal',
            fields=[
                ('sifraartikla', models.IntegerField(primary_key=True, serialize=False)),
                ('nazivartikla', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'artikal',
            },
        ),
        migrations.CreateModel(
            name='stavkakataloga',
            fields=[
                ('rednibroj', models.IntegerField(primary_key=True, serialize=False)),
                ('brojkataloga', models.IntegerField()),
                ('sifraartikla', models.IntegerField()),
                ('dimenzija', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('pdv', models.IntegerField()),
                ('naziv', models.CharField(max_length=25)),
                ('nazivartikla', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'stavkakataloga',
            },
        ),
        migrations.DeleteModel(
            name='katalog',
        ),
    ]
