# Generated by Django 3.1.5 on 2021-01-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0006_auto_20210122_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artikal',
            new_name='Album',
        ),
    ]
