# Generated by Django 3.1.5 on 2021-01-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0007_auto_20210122_0109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Artikal',
        ),
    ]
