# Generated by Django 3.1.5 on 2021-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0008_auto_20210122_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikalI',
            fields=[
                ('sifraartikla', models.IntegerField(primary_key=True, serialize=False)),
                ('nazivartikla', models.CharField(max_length=25)),
                ('aktuelnacena', models.IntegerField()),
            ],
            options={
                'db_table': 'artikal',
                'managed': True,
            },
        ),
    ]
