# Generated by Django 3.1.5 on 2021-01-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0009_artikali'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artikal',
        ),
        migrations.DeleteModel(
            name='ArtikalI',
        ),
        migrations.DeleteModel(
            name='stavkakataloga',
        ),
    ]
