# Generated by Django 3.1.5 on 2021-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0012_otpremnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzbenica',
            fields=[
                ('brojnarudzbenice', models.IntegerField(primary_key=True, serialize=False)),
                ('brojkataloga', models.IntegerField()),
                ('sifrazaposlenog', models.IntegerField()),
                ('pib', models.IntegerField()),
                ('brojracuna', models.IntegerField()),
                ('date', models.DateField()),
                ('napomena', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SOtpremnice',
            fields=[
                ('rednibroj', models.IntegerField(primary_key=True, serialize=False)),
                ('brojotpremnice', models.IntegerField()),
                ('sifraartikla', models.IntegerField()),
                ('kolicina', models.IntegerField()),
                ('pdv', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('napomena', models.CharField(max_length=25)),
                ('nazivartikla', models.CharField(max_length=25)),
                ('ukupnacena', models.IntegerField()),
            ],
        ),
    ]
